# Site
name: 'Davi Figueiredo'
description: 'I built a blog so I can tell my story and help others.'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'

baseurl: ''
email: 'davi.mello.28@gmail.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    davi:
      name:           Davi Figueiredo
      site:           https://davifigueiredo.com
      avatar:         https://avatars2.githubusercontent.com/u/3607502?s=460
      bio:            "IT Manager and Full-Stack Developer, enthusiast of decentralization. Designer, musician, and bodybuilder in free time."
      email:          davi.mello.28@gmail.com
      mastodon:       https://mastodon.social/@davifigueiredo

 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: davi
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
